### ISSUE TITLE
LimitExceeded on submission

### ISSUE THREAD

**Issue by Phunkyio** [Phnky/rimworld-godlike-mod#5]
Workshop: OnItemSubmitted failure. Result: LimitExceeded
Verse.Log:Error(String, Boolean)
Verse.Steam.Workshop:OnItemSubmitted(SubmitItemUpdateResult_t, Boolean)
Steamworks.CallResult`1:OnRunCallResult(IntPtr, IntPtr, Boolean, UInt64)
Steamworks.NativeMethods:SteamAPI_RunCallbacks()
Steamworks.SteamAPI:RunCallbacks()

**Comment by Jvella94** [comment]
#6 Fixed 👍

**Comment by Jvella94** [comment]
@Phnky all ok with the PR? :)
